add backend role to tf init cmd

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -65,27 +65,57 @@ jobs:
         id: fmt
         run: terraform fmt -check
         continue-on-error: true
+      ########################## testing ##########################
 
-      - name: Terraform Init and Workspaces
-        run: |
-          # Assume the role in Account B for terraform init
-          assume_role_output=$(aws sts assume-role \
-            --role-arn arn:aws:iam::590183831246:role/github-actions-tf-mgmt-role \
-            --role-session-name GitHubActionsInit)
+      # - name: Terraform Init and Workspaces
+      #   run: |
+      #     # Assume the role in Account B for terraform init
+      #     assume_role_output=$(aws sts assume-role \
+      #       --role-arn arn:aws:iam::590183831246:role/github-actions-tf-mgmt-role \
+      #       --role-session-name GitHubActionsInit)
 
-          export AWS_ACCESS_KEY_ID=$(echo $assume_role_output | jq -r .Credentials.AccessKeyId)
-          export AWS_SECRET_ACCESS_KEY=$(echo $assume_role_output | jq -r .Credentials.SecretAccessKey)
-          export AWS_SESSION_TOKEN=$(echo $assume_role_output | jq -r .Credentials.SessionToken)
+      #     export AWS_ACCESS_KEY_ID=$(echo $assume_role_output | jq -r .Credentials.AccessKeyId)
+      #     export AWS_SECRET_ACCESS_KEY=$(echo $assume_role_output | jq -r .Credentials.SecretAccessKey)
+      #     export AWS_SESSION_TOKEN=$(echo $assume_role_output | jq -r .Credentials.SessionToken)
 
-          terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${AWS_BUCKET_KEY_NAME}" -backend-config="region=${AWS_REGION}" -backend-config="workspace_key_prefix=${REPO_NAME}"
-          chmod +x ../../.github/workflows/utils/workspaces.sh
-          source ../../.github/workflows/utils/workspaces.sh $GITHUB_BRANCH_NAME
+      #     terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${AWS_BUCKET_KEY_NAME}" -backend-config="region=${AWS_REGION}" -backend-config="workspace_key_prefix=${REPO_NAME}"
+      #     chmod +x ../../.github/workflows/utils/workspaces.sh
+      #     source ../../.github/workflows/utils/workspaces.sh $GITHUB_BRANCH_NAME
 
       # - name: Terraform Workspaces
       #   id: workspaces
       #   run: |
       #     aws sts get-caller-identity
           
+
+      # - name: Terraform Validate
+      #   id: validate
+      #   run: terraform validate -no-color
+
+      # - name: Terraform Plan
+      #   id: plan
+      #   run: terraform plan -no-color
+      #   continue-on-error: true
+
+      # - name: Terraform Plan Status
+      #   if: steps.plan.outcome == 'failure'
+      #   run: exit 1
+      ########################## testing ##########################
+
+      # - name: Debug AWS CLI Configuration (Account B)
+      #   run: |
+      #     aws configure list
+      #     aws sts get-caller-identity
+
+      - name: Terraform Init
+        id: init
+        run: terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${AWS_BUCKET_KEY_NAME}" -backend-config="region=${AWS_REGION}" -backend-config="workspace_key_prefix=${REPO_NAME}" -backend-config="role_arn=${AWS_TF_ROLE}"
+
+      - name: Terraform Workspaces
+        id: workspaces
+        run: |
+          chmod +x ../../.github/workflows/utils/workspaces.sh
+          source ../../.github/workflows/utils/workspaces.sh $GITHUB_BRANCH_NAME
 
       - name: Terraform Validate
         id: validate
@@ -99,34 +129,6 @@ jobs:
       - name: Terraform Plan Status
         if: steps.plan.outcome == 'failure'
         run: exit 1
-
-      # - name: Debug AWS CLI Configuration (Account B)
-      #   run: |
-      #     aws configure list
-      #     aws sts get-caller-identity
-
-      # - name: Terraform Init
-      #   id: init
-      #   run: terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${AWS_BUCKET_KEY_NAME}" -backend-config="region=${AWS_REGION}" -backend-config="workspace_key_prefix=${REPO_NAME}"
-
-      # - name: Terraform Workspaces
-      #   id: workspaces
-      #   run: |
-      #     chmod +x ../../.github/workflows/utils/workspaces.sh
-      #     source ../../.github/workflows/utils/workspaces.sh $GITHUB_BRANCH_NAME
-
-  #     - name: Terraform Validate
-  #       id: validate
-  #       run: terraform validate -no-color
-
-  #     - name: Terraform Plan
-  #       id: plan
-  #       run: terraform plan -no-color
-  #       continue-on-error: true
-
-  #     - name: Terraform Plan Status
-  #       if: steps.plan.outcome == 'failure'
-  #       run: exit 1
 
   # apply:
   #   needs: plan
