comment out

diff --git a/.github/workflows/destroy.yml b/.github/workflows/destroy.yml
--- a/.github/workflows/destroy.yml
+++ b/.github/workflows/destroy.yml
@@ -24,44 +24,44 @@ jobs:
       - name: Git checkout
         uses: actions/checkout@v3
 
-      # - name: Set ENV variables
-      #   run: |
-      #     echo "REPO_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_ENV
-      #     if [[ $GITHUB_REF == refs/heads/main ]]; then
-      #       echo "Using QA Role"
-      #       echo "AWS_ROLE=${{ secrets.AWS_QA_ROLE }}" >> $GITHUB_ENV
-      #     elif [[ $GITHUB_REF == refs/heads/develop ]]; then
-      #       echo "Using Test Role"
-      #       echo "AWS_ROLE=${{ secrets.AWS_TEST_ROLE }}" >> $GITHUB_ENV
-      #     elif [[ $GITHUB_REF == refs/heads/feature/* || $GITHUB_REF == refs/heads/bugfix/* || $GITHUB_REF == refs/heads/task/* || $GITHUB_REF == refs/heads/hotfix/* ]]; then
-      #       echo "Using Dev Role"
-      #       echo "AWS_ROLE=${{ secrets.AWS_DEV_ROLE }}" >> $GITHUB_ENV
-      #     else
-      #       echo "Invalid branch name. Stopping the action."
-      #       exit 1
-      #     fi
+      - name: Set ENV variables
+        run: |
+          echo "REPO_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_ENV
+          if [[ $GITHUB_REF == refs/heads/main ]]; then
+            echo "Using QA Role"
+            echo "AWS_ROLE=${{ secrets.AWS_QA_ROLE }}" >> $GITHUB_ENV
+          elif [[ $GITHUB_REF == refs/heads/develop ]]; then
+            echo "Using Test Role"
+            echo "AWS_ROLE=${{ secrets.AWS_TEST_ROLE }}" >> $GITHUB_ENV
+          elif [[ $GITHUB_REF == refs/heads/feature/* || $GITHUB_REF == refs/heads/bugfix/* || $GITHUB_REF == refs/heads/task/* || $GITHUB_REF == refs/heads/hotfix/* ]]; then
+            echo "Using Dev Role"
+            echo "AWS_ROLE=${{ secrets.AWS_DEV_ROLE }}" >> $GITHUB_ENV
+          else
+            echo "Invalid branch name. Stopping the action."
+            exit 1
+          fi
         
-      # - name: Configure AWS credentials from AWS account
-      #   uses: aws-actions/configure-aws-credentials@v1
-      #   with:
-      #     role-to-assume: ${{ env.AWS_ROLE }}
-      #     aws-region: ${{ env.AWS_REGION }}
-      #     role-session-name: GitHub-OIDC-TERRAFORM
+      - name: Configure AWS credentials from AWS account
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          role-to-assume: ${{ env.AWS_ROLE }}
+          aws-region: ${{ env.AWS_REGION }}
+          role-session-name: GitHub-OIDC-TERRAFORM
 
-      # - name: Setup Terraform
-      #   uses: hashicorp/setup-terraform@v2
-      #   with:
-      #     terraform_version: 1.2.5
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v2
+        with:
+          terraform_version: 1.2.5
 
-      # - name: Terraform Init
-      #   id: init
-      #   run: terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${AWS_BUCKET_KEY_NAME}" -backend-config="region=${AWS_REGION}" -backend-config="workspace_key_prefix=${REPO_NAME}" -backend-config="role_arn=${AWS_TF_ROLE}"
+      - name: Terraform Init
+        id: init
+        run: terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${AWS_BUCKET_KEY_NAME}" -backend-config="region=${AWS_REGION}" -backend-config="workspace_key_prefix=${REPO_NAME}" -backend-config="role_arn=${AWS_TF_ROLE}"
 
-      # - name: Terraform Workspaces
-      #   id: workspaces
-      #   run: |
-      #     chmod +x ../../.github/workflows/utils/workspaces.sh
-      #     source ../../.github/workflows/utils/workspaces.sh $GITHUB_BRANCH_NAME
+      - name: Terraform Workspaces
+        id: workspaces
+        run: |
+          chmod +x ../../.github/workflows/utils/workspaces.sh
+          source ../../.github/workflows/utils/workspaces.sh $GITHUB_BRANCH_NAME
 
-      # - name: Terraform destroy
-      #   run: terraform destroy -auto-approve
+      - name: Terraform destroy
+        run: terraform destroy -auto-approve
